services:
  web-redis:
    build:
      context: .
    posts:
      - "8000:8000"
    volumes:
      - ./backend:/backend/app

    command: > 
      sh -c "python manage.py runserver 0.0.0.0:8000"
      