# Generated by Django 5.1.6 on 2025-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.PositiveIntegerField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
